### ISSUE TITLE
Hourly Cooldown Text

### ISSUE THREAD

**Issue by Baesm** [TheSowut/hearthstone#6]
Would be great if the text output had an hourly format as well. Right now, our server cooldown is 12 hours, and error text says "719 minutes".

**Comment by TheSowut** [comment]
Noted, will look into it.
Thanks for the feedback!

**Comment by TheSowut** [comment]
@Baesm Issue has been addressed in #7.
If you'd like you can check the [changelog](https://www.spigotmc.org/resources/hearthstone.107248/update?update=490663), which includes a picture of the new format featuring hours.
Thanks a lot for the feedback and I'm glad you're enjoying the plugin :)
